apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - name: app
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: app
          image: cc-ms-k8s-training.common.repositories.cloud.sap/users-<YOUR C/D/I-NUMBER>
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: "server.port"
              value: "8081"
      imagePullSecrets:
        - name: regcred
