apiVersion: v1
kind: Service
metadata:
  name: greetings
spec:
  type: ClusterIP
  selector:
    app: greetings
  ports:
    - name: app
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings
spec:
  selector:
    matchLabels:
      app: greetings
  replicas: 1
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
        - name: app
          image: cc-ms-k8s-training.common.repositories.cloud.sap/greetings-<YOUR C/D/I-NUMBER>
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: USERS_SERVICE_HOST
              value: "users.default.svc.cluster.local"
            - name: USERS_SERVICE_PORT
              value: "8081"
      imagePullSecrets:
        - name: regcred
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: greetings
spec:
  rules:
    - host: app.ingress.<CLUSTER>.kyma.ondemand.com
      http:
        paths:
          - backend:
              service:
                name: greetings
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - app.ingress.<CLUSTER>.kyma.ondemand.com
      secretName: kyma-gateway-certs
